[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
gm_contract = "HpaRqapKNdoWUXhWnbzubaoKXADHpY7SBy8b4QpZ5UqM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/h123mn/.config/solana/id.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/create-pool.ts"
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/deposit-prize.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/withdraw-prize.ts"
