[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
gm_contract = "Ay6NVBNkzTkTXduiF6yFybfcipAjXriYr17LL8edb6YE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mac/.config/solana/id.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/create-pool.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/deposit-prize.ts"
